name: merge-code-coverage

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        shardIndex: [1]
        shardTotal: [1]

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          # cache: "npm" - enabled by default for npm

      - run: npm ic
      - run: npm run test:unit -- --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        env:
          FORCE_COLOR: true

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-unit-${{ matrix.shardIndex }}
          path: coverage-reports
          retention-days: 1
          include-hidden-files: true
          if-no-files-found: error

  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        shardIndex: [1, 2]
        shardTotal: [2]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"

      - run: npm ic
      - run: npx playwright install chromium --with-deps
      - run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        env:
          FORCE_COLOR: true

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-e2e-${{ matrix.shardIndex }}
          path: coverage-reports
          retention-days: 1
          include-hidden-files: true
          if-no-files-found: error

      - uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: test-results
          path: test-results

  merge-coverage:
    name: merge-coverage
    runs-on: ubuntu-latest
    needs: [unit-test, e2e-test]

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"

      - uses: actions/download-artifact@v6
        with:
          path: coverage-reports
          pattern: coverage-*
          merge-multiple: true

      - run: npm ic
      - run: npm run test:merge
        env:
          FORCE_COLOR: true

      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./coverage-reports/merged"

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
